Repository multidadosti-erp/odoo-brasil-addons, pull requests merged in 2018-06, with the labels that each got.

#88 T0121 - Ajustar texto do e-mail de convite do sistema.
  br_base/i18n/pt_BR.po
Labels: Type: New feature, Version: 11.0

#93 T0863 - Adequar br_account a mudanças propostas em financeiro
  br_account/i18n/pt_BR.po
  br_account/models/account_move.py
  br_account/models/account_move_line.py
  br_account/tests/test_account_invoice.py
  br_account/views/account_move.xml
Labels: Version: 11.0

#94 T0864 - Adequar br_account_payment a mudanças propostas em financeiro
  br_account_payment/__init__.py
  br_account_payment/__manifest__.py
  br_account_payment/models/__init__.py
  br_account_payment/models/account_invoice.py
  br_account_payment/models/account_journal.py
  br_account_payment/models/account_move.py
  br_account_payment/models/account_move_line.py
  br_account_payment/models/account_payment.py
  br_account_payment/models/payment_mode.py
  br_account_payment/views/account_move.xml
  br_account_payment/views/account_move_line.xml
  br_account_payment/views/account_payment.xml
  br_account_payment/views/br_account_payment.xml
  br_account_payment/wizards/__init__.py
  br_account_payment/wizards/account_move_alter_date.py
  br_account_payment/wizards/account_move_alter_date.xml
  br_account_payment/wizards/account_move_alter_operation.py
  br_account_payment/wizards/account_move_alter_operation.xml
Labels: Version: 11.0

#95 T0856 - Mudança de Menu de faturamento
  br_nfe/__manifest__.py
  br_nfe/views/inutilized_nfe.xml
  br_nfe/wizard/export_nfe.xml
  br_nfe/wizard/inutilize_nfe_numeration.xml
Labels: Type: New feature, Version: 11.0

#98 T0921 - Ajusta geração de movimentações a partir de parcelas
  br_account/models/account_invoice.py
  br_account/tests/test_account_invoice.py
  br_account/tests/test_base.py
Labels: Type: Bug, Version: 11.0
