Repository multidadosti-erp/odoo-brasil-addons, pull requests merged in 2018-08, with the labels that each got.

#123 T1152 - HOTFIX-Correções no módulo financeiro.
  br_account_payment/views/account_move.xml
Labels: Priority: Highest, Stage: In progress, Type: Bug, Version: 11.0

#126 T1180 - Ajustar operação de cancelamento de títulos
  br_account/models/account_move.py
Labels: Type: Bug, Version: 11.0

#128 T1188 - Adicionar limite nas tarefas de cron da NF
  br_account_einvoice/models/invoice_electronic.py
Labels: Type: Improvement, Version: 11.0

#129 T1263 - Erro na pesquisa de CEP
  br_base/data/res.state.city.csv
Labels: Type: Bug, Version: 11.0

#130 T1264 - Acertar Tradução Cadastro dos Contatos
  br_base/i18n/pt_BR.po
Labels: Version: 11.0

#132 T1079 - Ao cancelar o cadastro de um novo usuário, o sistema exibe uma mensagem em ingles.
  br_base/i18n/pt_BR.po
Labels: Type: New feature, Version: 11.0

#133 T1302 - Adicionar tag 'noupdate' nos arquivos data
  br_account/demo/product_fiscal_classification.xml
  br_account/demo/product_template.xml
  br_account/demo/res_partner.xml
  br_account_einvoice/data/br_account_einvoice.xml
  br_nfe/demo/res_partner.xml
  br_nfse/demo/product_demo.xml
  br_nfse_paulistana/data/br_nfse_paulistana.xml
  br_sale/security/l10n_br_sale_security.xml
Labels: Type: New feature, Version: 11.0

#136 T1354 - Ao criar uma fatura de fornecedor, o sistema não esta gerando o contas a pagar
  br_account/models/account_move.py
Labels: Type: Bug, Version: 11.0

#134 T1327 - Erro ao instalar br_sale
  br_sale/views/sale_order.xml
Labels: Category: Frontend, Type: Bug, Version: 11.0

#138 T1384 - Sistema esta mostrando os Estágios do CRM apenas no Debug
  br_crm/views/crm_opportunity.xml
Labels: Type: New feature, Version: 11.0

#139 [FIX] Corrige tradução do campo 'Customer'
  br_crm/i18n/pt_BR.po
Labels: Category: Frontend, Type: Bug, Version: 11.0

#140 T1385 - Criar funcionalidade de arquivar Plano de contas
  br_account/i18n/pt_BR.po
  br_account/models/account_account.py
  br_account/views/account_account.xml
Labels: Type: New feature, Version: 11.0
