Repository multidadosti-erp/odoo-brasil-addons, pull requests merged in 2018-05, with the labels that each got.

#74 T0651 - Corrigir erro de view (js) quando adicionamos linha de fatura
  br_account/views/account_invoice_line.xml
Labels: Type: Bug, Version: 11.0

#73 T0495 - Adicionar opção de confirmação no doc. eletronico
  br_account_einvoice/views/invoice_electronic.xml
Labels: Stage: Review, Type: Improvement, Version: 11.0

#72 T0179 - Adicionar opção de confirmação na fatura
  br_account/views/account_invoice.xml
Labels: Type: Improvement, Version: 11.0

#76 T0714 - Faltam Campos na Tela de Receber
  br_account/views/account_move_line.xml
Labels: Category: Frontend, Version: 11.0

#77 T0733 - Erro de digitação na mensagem da fatura
  br_account/views/account_invoice.xml
Labels: Category: Frontend, Type: Bug

#78 T0705 - Traduzir Payment Modes - Contabilidade
  br_account_payment/i18n/pt_BR.po
Labels: Type: New feature, Version: 11.0

#79 T0732 - Atualizar versão das dependências python
  requirements.txt
Labels: Type: Improvement, Version: 11.0

#80 T0734 - Erro de digitação slogan da empresa
  br_base/i18n/pt_BR.po
Labels: Type: Bug, Version: 11.0

#81 T0766 - Remover botão de impressão da Cotação
  br_sale/views/sale_view.xml
Labels: Level: Easy, Type: New feature, Version: 11.0

#84 T0740 - Corrigir mensagem ao excluir roles
  br_base/i18n/pt_BR.po
Labels: Type: New feature, Version: 11.0

#86 T0834 - Cadastro de Produto - Acerto Cadastral
  br_account/models/product_template.py
Labels: Type: New feature, Version: 11.0
