Repository multidadosti-erp/odoo-brasil-addons, pull requests merged in 2018-03, with the labels that each got.

#42 Acertar o Agrupamento das Faturas de Clientes
  br_account_einvoice/models/account_invoice.py
Labels: Type: Improvement, Version: 11.0

#56 [FIX] Atualização do arquivo de tradução do módulo 'br_crm'
  br_crm/i18n/pt_BR.po
Labels: Type: Improvement, Version: 11.0

#60 [MIG] br_stock_account: Migration to 11.0
  br_stock_account/__init__.py
  br_stock_account/__manifest__.py
  br_stock_account/models/__init__.py
  br_stock_account/models/account_invoice.py
  br_stock_account/models/account_invoice_line.py
  br_stock_account/views/account_invoice.xml
  br_stock_account/views/account_invoice_line.xml
Labels: Type: Migration, Version: 11.0

#62 [MIG] br_purchase: Migration to 11.0
  br_purchase/__init__.py
  br_purchase/__manifest__.py
  br_purchase/models/__init__.py
  br_purchase/models/account_invoice.py
  br_purchase/models/purchase_order.py
  br_purchase/models/purchase_order_line.py
  br_purchase/views/purchase_order.xml
Labels: Type: Migration, Version: 11.0

#61 [MIG] br_sale_stock: Migration to 11.0
  br_sale_stock/__init__.py
  br_sale_stock/__manifest__.py
  br_sale_stock/models/__init__.py
  br_sale_stock/models/sale_order.py
  br_sale_stock/models/sale_order_line.py
  br_sale_stock/tests/__init__.py
  br_sale_stock/tests/test_br_sale_stock.py
  br_sale_stock/views/sale_stock.xml
Labels: Type: Migration, Version: 11.0

#63 [MIG] br_purchase_stock 11.0
  br_purchase_stock/__init__.py
  br_purchase_stock/__manifest__.py
  br_purchase_stock/models/__init__.py
  br_purchase_stock/models/account_invoice.py
  br_purchase_stock/models/purchase_order.py
  br_purchase_stock/models/purchase_order_line.py
  br_purchase_stock/views/purchase_order.xml
Labels: Type: Migration, Version: 11.0

#66 [FIX] Move campo 'internal_number' para br_account
  br_account/models/account_invoice.py
  br_account_einvoice/models/account_invoice.py
Labels: Type: Bug, Version: 11.0
